CREATE OR REPLACE TRIGGER hire_date_update
BEFORE UPDATE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :OLD.JOB_ID != :NEW.JOB_ID THEN
         :NEW.HIRE_DATE := TRUNC(SYSDATE);
    END IF;
END;
/



SELECT EMPLOYEE_ID, JOB_ID, HIRE_DATE 
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 206; 


UPDATE EMPLOYEES
SET JOB_ID = 'AC_AC'
WHERE EMPLOYEE_ID = 206; 



SELECT EMPLOYEE_ID, JOB_ID, HIRE_DATE 
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 206;